# Base de Dados
spring.datasource.url=jdbc:sqlserver://${DB_HOST:localhost}:1433;databaseName=BennysDB;encrypt=true;trustServerCertificate=true;
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:teu_password_aqui}

# Segurança (JWT)
api.security.token.secret=${JWT_SECRET:uma_chave_secreta_e_longa_aqui}

# SendGrid
sendgrid.api.key=${SENDGRID_API_KEY:tua_chave_api_aqui}

# Configurações de Ficheiros
spring.servlet.multipart.max-file-size=100MB


